=head1 Personal misc files.

=head2 Currently:

=over 

=item * el,  an elimage's perl version. # What is elimage? see L<http://img.vim-cn.com>

=item * zshrc, my .zshrc

=item * tips, add random tips.

=item * extractable, to extract table creating strings from SQL dump file base on index file.

=item * compare, compare two files' text contents  by line, no matter the line's order in file.

=item * reorder, re-order the Amego style file by the index's suffix.

=back

